package servis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-12-19T13:53:57.885+01:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "CountryDetailsServiceService",
                  wsdlLocation = "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/CountryDetailsService?wsdl",
                  targetNamespace = "http://countries.milan.jovic.dmi.uns.ac.rs/")
public class CountryDetailsServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://countries.milan.jovic.dmi.uns.ac.rs/", "CountryDetailsServiceService");
    public final static QName CountryDetailsServicePort = new QName("http://countries.milan.jovic.dmi.uns.ac.rs/", "CountryDetailsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/CountryDetailsService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CountryDetailsServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/CountryDetailsService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CountryDetailsServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CountryDetailsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryDetailsServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CountryDetailsServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CountryDetailsServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CountryDetailsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CountryDetailsRemoteService
     */
    @WebEndpoint(name = "CountryDetailsServicePort")
    public CountryDetailsRemoteService getCountryDetailsServicePort() {
        return super.getPort(CountryDetailsServicePort, CountryDetailsRemoteService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryDetailsRemoteService
     */
    @WebEndpoint(name = "CountryDetailsServicePort")
    public CountryDetailsRemoteService getCountryDetailsServicePort(WebServiceFeature... features) {
        return super.getPort(CountryDetailsServicePort, CountryDetailsRemoteService.class, features);
    }

}
