package servis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-12-19T13:53:57.748+01:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://countries.milan.jovic.dmi.uns.ac.rs/", name = "CountryDetailsRemoteService")
@XmlSeeAlso({ObjectFactory.class})
public interface CountryDetailsRemoteService {

    @WebMethod
    @RequestWrapper(localName = "getInfoForCountry", targetNamespace = "http://countries.milan.jovic.dmi.uns.ac.rs/", className = "servis.GetInfoForCountry")
    @ResponseWrapper(localName = "getInfoForCountryResponse", targetNamespace = "http://countries.milan.jovic.dmi.uns.ac.rs/", className = "servis.GetInfoForCountryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public servis.CountryDetailsPOJO getInfoForCountry(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
