package servis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-12-19T15:18:49.509+01:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebServiceClient(name = "ConferenceWSService",
                  wsdlLocation = "http://localhost:8080/ConferenceEJB/ConferenceWS?wsdl",
                  targetNamespace = "http://rzk/")
public class ConferenceWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rzk/", "ConferenceWSService");
    public final static QName ConferenceWSPort = new QName("http://rzk/", "ConferenceWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ConferenceEJB/ConferenceWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConferenceWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ConferenceEJB/ConferenceWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConferenceWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConferenceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConferenceWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConferenceWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConferenceWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConferenceWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConferenceWSRemote
     */
    @WebEndpoint(name = "ConferenceWSPort")
    public ConferenceWSRemote getConferenceWSPort() {
        return super.getPort(ConferenceWSPort, ConferenceWSRemote.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConferenceWSRemote
     */
    @WebEndpoint(name = "ConferenceWSPort")
    public ConferenceWSRemote getConferenceWSPort(WebServiceFeature... features) {
        return super.getPort(ConferenceWSPort, ConferenceWSRemote.class, features);
    }

}
