package servis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2018-12-19T15:18:49.382+01:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://rzk/", name = "ConferenceWSRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface ConferenceWSRemote {

    @WebMethod
    @RequestWrapper(localName = "getAllConference", targetNamespace = "http://rzk/", className = "servis.GetAllConference")
    @ResponseWrapper(localName = "getAllConferenceResponse", targetNamespace = "http://rzk/", className = "servis.GetAllConferenceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<servis.Conference> getAllConference(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
